/**
 * Enum for task status values.
 */
export enum TaskStatus {
  Todo = "todo",
  InProgress = "in-progress",
  Completed = "completed",
}

/**
 * Enum for task priority values.
 */
export enum TaskPriority {
  Low = "low",
  Medium = "medium",
  High = "high",
}

/**
 * Represents a Task document in Cosmos DB.
 */
export interface Task {
  id: string;
  organizationId: string;
  title: string;
  description?: string;
  dueDate?: string;
  priority?: TaskPriority;
  status: TaskStatus;
  tags?: string[];
  customFields?: Record<string, any>;
}

/**
 * Input type for creating a new task.
 * The `id` is auto-generated by the service layer.
 */
export type CreateTaskInput = Omit<Task, "id">;

/**
 * Input type for updating an existing task.
 * Only allows updating mutable fields (not id or organizationId).
 */
export type UpdateTaskInput = Partial<Omit<Task, "id" | "organizationId">>;

/**
 * Paginated response wrapper.
 */
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

/**
 * Query options for listing tasks.
 */
export interface TaskQueryOptions {
  organizationId: string;
  page?: number;
  pageSize?: number;
  search?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  sortBy?: string;
  sortOrder?: "asc" | "desc";
}
